nodes:
  default_list:
    - USD
    - EUR
    - GBP
    - JPY
    - CHF
    - CAD
    - AUD
    - NZD
    - SEK
    - NOK
  anchor_node: USD

cost_model:
  base_cost: 10
  extra_cost: 5

generated_data:
  available_nodes:
    - USD
    - EUR
    - GBP
    - JPY
    - CHF
    - CAD
    - AUD
    - NZD
    - SEK
    - NOK
    - SGD
    - HKD
    - MXN
    - BRL
    - INR
    - CNY
    - KRW
    - ZAR
    - PLN
    - CZK
    - TRY
    - AED
    - SAR
    - THB
    - MYR
    - IDR
    - PHP
